# -*- coding: utf-8 -*-
"""List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GY6X5r7RK5C_I4bzXHQlwa9B0941JZE1
"""

Data= [10,3.44,"four","himanshi",119.3 ]

Data[0:6:2]

Data[1].real

Data[::2]

Data

Data[0:3]

Data[-1]

Data[-1:-4:-2]

Data[-1]

Data[1:4:-2]

Data[-5:-1:2]

Data.append(65)

Data.pop(2)

L=["colour", 45 ,34 ,67 ,"true" ,"class" ]

S=["brain",45,60]

L(S)+L

L1=[23,"add",45,60,56.4]

L1.append(56)

L1

L1