# -*- coding: utf-8 -*-
"""mini project - atm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16mjHqtStXZJGJXFu293XghjoucoNs7ex
"""

Options = ["Balance", "Withdraw", "Change PIN", "Exit"]

print("----Welcome To ATM Services----")
print("Please Insert Your Card")
print("Your Card is Inserted")

if input("Please Enter Your Pin: ") == "1234":
    print("Your Pin is Accepted")
    for I in Options:
        print(I)

    SERVICES = int(input("Please Select Your Option: "))
    if SERVICES == 1:
        print("Your Balance is: 12")
    elif SERVICES == 2:
        WITHDRAW = int(input("Please Enter The Amount You Want To Withdraw: "))
        print(f"You Have Withdrawn: {WITHDRAW}")
    elif SERVICES == 3:
        NEW_PIN = input("Please Enter Your New Pin: ")
        print(f"Your Pin Has Been Changed To: {NEW_PIN}")
    elif SERVICES == 4:
        print("Thank You For Using Our Services")
    else:
        print("Invalid Option Selected")
else:
    print("Invalid Pin")

def deposit():
  pin = int(input("Enter PIN: "))
  if pin != customer["PIN"]:
    print("Invalid PIN")
  else:
    money=int(input("Enter amount to be deposited: "))
    customer["Amount"] = customer["Amount"] + money
def withdrawal():
  pin = int(input("Enter PIN: "))
  if pin != customer["PIN"]:
    print("Invalid PIN")
  else:
    money=int(input("Enter amount to be withdrawn: "))
    if customer["Amount"] < money:
      print("Not enough balance")
    else:
      customer["Amount"] = customer["Amount"] - money
      return customer["Amount"]
def amount():
  print(customer["Amount"])

def pin_change():
  pin = int(input("Enter PIN: "))
  if pin != customer["PIN"]:
    print("Invalid PIN")
  else:
    npin = int(input("Enter new PIN: "))
    n2pin = int(input("Confirm PIN"))
    if npin != n2pin:
      print("Not same")
    else:
      print("PIN changed succesfully")

customer = {"Card number" : 1234 , "PIN" : 789 , "Amount" : 4500 }
cnum = int(input("Enter Card number: "))
if cnum != customer["Card number"]:
  print("Invalid Card Number")
else:
  service = int(input("Enter service:\n 1-DEPOSIT \n 2-WITHDRAWAL \n 3-PIN CHANGE \n 4-AMOUNT CHECK \n "))
  if service == 1:
    deposit()
  elif service == 2:
    print("new amount :" ,withdrawal())
  elif service == 3:
    pin_change()
  elif service == 4:
    amount()
  else:
    print("Invalid choice")